name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Gradle
        run: |
          wget -q https://services.gradle.org/distributions/gradle-7.2-bin.zip
          unzip -q gradle-7.2-bin.zip
          export PATH=$PATH:$PWD/gradle-7.2/bin
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Run Tests
        run: ./gradlew build

  build:
    name: Build Apk
    runs-on: ubuntu-latest
    steps:
    - name: Install Gradle
      run: |
        wget -q https://services.gradle.org/distributions/gradle-7.2-bin.zip
        unzip -q gradle-7.2-bin.zip
        export PATH=$PATH:$PWD/gradle-7.2/bin
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
